apiVersion: v1
kind: Service
metadata:
  name: wsrestauditorialst
  namespace: dev
spec:
  ports:
    - name: http
      port: 18081
    - name: https
      port: 443
  type: LoadBalancer    
  selector:
    app: wsrestauditorialst